// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Request struct {
	Password string  `json:"password"`
	Rules    []*Rule `json:"rules"`
}

type Response struct {
	Verify  bool      `json:"verify"`
	NoMatch []*string `json:"noMatch"`
}

type Rule struct {
	Rule  string `json:"rule"`
	Value int    `json:"value"`
}
